/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.arithmetic.arithmetic.impl;

import org.eclipse.emf.ecore.EClass;

import uk.ac.kcl.inf.arithmetic.arithmetic.ArithmeticPackage;
import uk.ac.kcl.inf.arithmetic.arithmetic.NumberExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Number Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NumberExpressionImpl extends ExpressionImpl implements NumberExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NumberExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ArithmeticPackage.Literals.NUMBER_EXPRESSION;
  }

} //NumberExpressionImpl
