/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.arithmetic.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.inf.arithmetics.ui.internal.ArithmeticsActivator;

public class ArithmeticUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ArithmeticsActivator.getInstance().getInjector("uk.ac.kcl.inf.arithmetic.Arithmetic");
	}

}
