/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.arithmetic.validation;

import org.eclipse.xtext.validation.Check;
import uk.ac.kcl.inf.arithmetic.arithmetic.ArithmeticPackage;
import uk.ac.kcl.inf.arithmetic.arithmetic.IntLiteral;
import uk.ac.kcl.inf.arithmetic.validation.AbstractArithmeticValidator;

/**
 * This class contains custom validation rules.
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ArithmeticValidator extends AbstractArithmeticValidator {
  public static final String INVALID_NUMBER = "uk.ac.kcl.inf.arithmetics.INVALID_NUMBER";
  
  @Check
  public void checkIntLiteralIsPositiveNumber(final IntLiteral intl) {
    int _num = intl.getNum();
    boolean _equals = (_num == 0);
    if (_equals) {
      this.warning("All the numbers should be positive numbers", 
        ArithmeticPackage.Literals.INT_LITERAL__NUM, 
        ArithmeticValidator.INVALID_NUMBER);
    }
  }
}
