/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.arithmetic;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ArithmeticRuntimeModule extends AbstractArithmeticRuntimeModule {
}
