/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.arithmetic;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ArithmeticStandaloneSetup extends ArithmeticStandaloneSetupGenerated {

	public static void doSetup() {
		new ArithmeticStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
