/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.arithmetic.ui.quickfix;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.model.edit.IMultiModification;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;
import uk.ac.kcl.inf.arithmetic.arithmetic.IntLiteral;
import uk.ac.kcl.inf.arithmetic.validation.ArithmeticValidator;

/**
 * Custom quickfixes.
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class ArithmeticQuickfixProvider extends DefaultQuickfixProvider {
  @Fix(ArithmeticValidator.INVALID_NUMBER)
  public void changeTheNumber(final Issue issue, final IssueResolutionAcceptor acceptor) {
    final IMultiModification<EObject> _function = (EObject element) -> {
      final IntLiteral decl = ((IntLiteral) element);
      decl.setNum(1);
    };
    acceptor.<EObject>acceptMulti(issue, "A positive number", "change the number to a positive one.", null, _function);
  }
}
