/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.arithmetic.scoping;

import uk.ac.kcl.inf.arithmetic.scoping.AbstractArithmeticScopeProvider;

/**
 * This class contains custom scoping description.
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ArithmeticScopeProvider extends AbstractArithmeticScopeProvider {
}
