/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.arithmetic.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractArithmeticScopeProvider extends DelegatingScopeProvider {
}
