/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.arithmetic.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.arithmetics.ui.internal.ArithmeticsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ArithmeticExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ArithmeticsActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ArithmeticsActivator activator = ArithmeticsActivator.getInstance();
		return activator != null ? activator.getInjector(ArithmeticsActivator.UK_AC_KCL_INF_ARITHMETIC_ARITHMETIC) : null;
	}

}
