/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.arithmetic.arithmetic;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Addition Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.arithmetic.arithmetic.AdditionStatement#getAddend1 <em>Addend1</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.arithmetic.arithmetic.AdditionStatement#getOperator <em>Operator</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.arithmetic.arithmetic.AdditionStatement#getAddend2 <em>Addend2</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.arithmetic.arithmetic.ArithmeticPackage#getAdditionStatement()
 * @model
 * @generated
 */
public interface AdditionStatement extends Statement, Expression
{
  /**
   * Returns the value of the '<em><b>Addend1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Addend1</em>' containment reference.
   * @see #setAddend1(Expression)
   * @see uk.ac.kcl.inf.arithmetic.arithmetic.ArithmeticPackage#getAdditionStatement_Addend1()
   * @model containment="true"
   * @generated
   */
  Expression getAddend1();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.arithmetic.arithmetic.AdditionStatement#getAddend1 <em>Addend1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Addend1</em>' containment reference.
   * @see #getAddend1()
   * @generated
   */
  void setAddend1(Expression value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see #setOperator(String)
   * @see uk.ac.kcl.inf.arithmetic.arithmetic.ArithmeticPackage#getAdditionStatement_Operator()
   * @model
   * @generated
   */
  String getOperator();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.arithmetic.arithmetic.AdditionStatement#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see #getOperator()
   * @generated
   */
  void setOperator(String value);

  /**
   * Returns the value of the '<em><b>Addend2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Addend2</em>' containment reference.
   * @see #setAddend2(Expression)
   * @see uk.ac.kcl.inf.arithmetic.arithmetic.ArithmeticPackage#getAdditionStatement_Addend2()
   * @model containment="true"
   * @generated
   */
  Expression getAddend2();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.arithmetic.arithmetic.AdditionStatement#getAddend2 <em>Addend2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Addend2</em>' containment reference.
   * @see #getAddend2()
   * @generated
   */
  void setAddend2(Expression value);

} // AdditionStatement
