/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.arithmetic.arithmetic;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multiplication Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.arithmetic.arithmetic.MultiplicationStatement#getMultiplier1 <em>Multiplier1</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.arithmetic.arithmetic.MultiplicationStatement#getMultiplier2 <em>Multiplier2</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.arithmetic.arithmetic.ArithmeticPackage#getMultiplicationStatement()
 * @model
 * @generated
 */
public interface MultiplicationStatement extends Statement, Expression
{
  /**
   * Returns the value of the '<em><b>Multiplier1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Multiplier1</em>' containment reference.
   * @see #setMultiplier1(Expression)
   * @see uk.ac.kcl.inf.arithmetic.arithmetic.ArithmeticPackage#getMultiplicationStatement_Multiplier1()
   * @model containment="true"
   * @generated
   */
  Expression getMultiplier1();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.arithmetic.arithmetic.MultiplicationStatement#getMultiplier1 <em>Multiplier1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Multiplier1</em>' containment reference.
   * @see #getMultiplier1()
   * @generated
   */
  void setMultiplier1(Expression value);

  /**
   * Returns the value of the '<em><b>Multiplier2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Multiplier2</em>' containment reference.
   * @see #setMultiplier2(Expression)
   * @see uk.ac.kcl.inf.arithmetic.arithmetic.ArithmeticPackage#getMultiplicationStatement_Multiplier2()
   * @model containment="true"
   * @generated
   */
  Expression getMultiplier2();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.arithmetic.arithmetic.MultiplicationStatement#getMultiplier2 <em>Multiplier2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Multiplier2</em>' containment reference.
   * @see #getMultiplier2()
   * @generated
   */
  void setMultiplier2(Expression value);

} // MultiplicationStatement
