/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.arithmetic.arithmetic;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Number Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.inf.arithmetic.arithmetic.ArithmeticPackage#getNumberExpression()
 * @model
 * @generated
 */
public interface NumberExpression extends Expression
{
} // NumberExpression
