/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.arithmetic.arithmetic;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Power Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.arithmetic.arithmetic.PowerStatement#getBasenumber <em>Basenumber</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.arithmetic.arithmetic.PowerStatement#getTimes <em>Times</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.arithmetic.arithmetic.ArithmeticPackage#getPowerStatement()
 * @model
 * @generated
 */
public interface PowerStatement extends Statement, Expression
{
  /**
   * Returns the value of the '<em><b>Basenumber</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Basenumber</em>' containment reference.
   * @see #setBasenumber(Expression)
   * @see uk.ac.kcl.inf.arithmetic.arithmetic.ArithmeticPackage#getPowerStatement_Basenumber()
   * @model containment="true"
   * @generated
   */
  Expression getBasenumber();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.arithmetic.arithmetic.PowerStatement#getBasenumber <em>Basenumber</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Basenumber</em>' containment reference.
   * @see #getBasenumber()
   * @generated
   */
  void setBasenumber(Expression value);

  /**
   * Returns the value of the '<em><b>Times</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Times</em>' attribute.
   * @see #setTimes(int)
   * @see uk.ac.kcl.inf.arithmetic.arithmetic.ArithmeticPackage#getPowerStatement_Times()
   * @model
   * @generated
   */
  int getTimes();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.arithmetic.arithmetic.PowerStatement#getTimes <em>Times</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Times</em>' attribute.
   * @see #getTimes()
   * @generated
   */
  void setTimes(int value);

} // PowerStatement
