/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.arithmetic.arithmetic;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Subtraction Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.arithmetic.arithmetic.SubtractionStatement#getMinuend <em>Minuend</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.arithmetic.arithmetic.SubtractionStatement#getSubtrahend <em>Subtrahend</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.arithmetic.arithmetic.ArithmeticPackage#getSubtractionStatement()
 * @model
 * @generated
 */
public interface SubtractionStatement extends Statement, Expression
{
  /**
   * Returns the value of the '<em><b>Minuend</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Minuend</em>' containment reference.
   * @see #setMinuend(Expression)
   * @see uk.ac.kcl.inf.arithmetic.arithmetic.ArithmeticPackage#getSubtractionStatement_Minuend()
   * @model containment="true"
   * @generated
   */
  Expression getMinuend();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.arithmetic.arithmetic.SubtractionStatement#getMinuend <em>Minuend</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Minuend</em>' containment reference.
   * @see #getMinuend()
   * @generated
   */
  void setMinuend(Expression value);

  /**
   * Returns the value of the '<em><b>Subtrahend</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subtrahend</em>' containment reference.
   * @see #setSubtrahend(Expression)
   * @see uk.ac.kcl.inf.arithmetic.arithmetic.ArithmeticPackage#getSubtractionStatement_Subtrahend()
   * @model containment="true"
   * @generated
   */
  Expression getSubtrahend();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.arithmetic.arithmetic.SubtractionStatement#getSubtrahend <em>Subtrahend</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subtrahend</em>' containment reference.
   * @see #getSubtrahend()
   * @generated
   */
  void setSubtrahend(Expression value);

} // SubtractionStatement
