/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.arithmetic.ide;


/**
 * Use this class to register ide components.
 */
public class ArithmeticIdeModule extends AbstractArithmeticIdeModule {
}
