/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.arithmetic.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.inf.arithmetic.ArithmeticRuntimeModule;
import uk.ac.kcl.inf.arithmetic.ArithmeticStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ArithmeticIdeSetup extends ArithmeticStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ArithmeticRuntimeModule(), new ArithmeticIdeModule()));
	}
	
}
